name: Build Desktop Apps

on:
  workflow_dispatch:
    inputs:
      ollama_url:
        description: 'Ollama URL (optional, defaults to http://127.0.0.1:11434)'
        required: false
        default: 'http://127.0.0.1:11434'
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev \
            build-essential curl wget file libssl-dev libgtk-3-dev \
            libayatana-appindicator3-dev librsvg2-dev patchelf libsoup2.4-dev

      - name: Install frontend dependencies
        working-directory: apps/desktop
        run: npm install

      - name: Verify icons exist
        working-directory: apps/desktop/src-tauri/icons
        shell: bash
        run: |
          echo "Checking for required icon files..."
          ls -la icon.ico icon.icns 32x32.png 128x128.png 128x128@2x.png || echo "Some icons missing but build will continue"

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: apps/desktop

      - name: Upload Windows Installer
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: apps/desktop/src-tauri/target/release/bundle/msi/*.msi

      - name: Upload macOS Installer
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: apps/desktop/src-tauri/target/release/bundle/dmg/*.dmg

      - name: Upload Linux Packages
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: |
            apps/desktop/src-tauri/target/release/bundle/deb/*.deb
            apps/desktop/src-tauri/target/release/bundle/appimage/*.AppImage
